### ISSUE TITLE
pandas objects wrt. flask-caching and webviz_store

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-config#211]
Flask caching with objects as input introduces a risk of not capturing changes in the object.
Read the warning under [memoization in the Flask documentation](https://flask-caching.readthedocs.io/en/latest/#memoization). Flask only checks the `repr()` of the object in the input, which might not by unique. The issue has been encountered with Pandas in Webviz, but can occur with any object instance that doesn't have a unique `repr()` output. 

Temporary solution is **to avoid using other input types than basic Python types** for `@CACHE.memoize` decorated methods. E.g. converting DataFrames to dict.

**Comment by anders-kiaer** [comment]
Yes, complex objects needs to have a unique `__repr__` representation in order to be cached correctly by `flask-cache`.

Would be interesting to investigate how costly turning it into simple structures (e.g. dict) versus hashing the content is. If the latter is faster (I would perhaps expect it to be), and caching of dataframes is necessary (maybe for most use cases it is not necessary?), one solution (which would solve the problem for all plugins, but at the same time is quite hacky) is to monkey-patch the `pandas.DatafFrame` `__repr__` function by appending a hash of the data in the `DataFrame` `__repr__`.

**Comment by anders-kiaer** [comment]
Since `pandas.DataFrame` and `pandas.Series`are so commonly used, and they don't have a well-behainv `__repr__` in the context of using it as cache has, we could perhaps investigate special-casing them and use [`pandas.util.hash_pandas_object(some_df)`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.util.hash_pandas_object.html) instead of `__repr__` for those types.
