### ISSUE TITLE
Relax install requirements

### ISSUE THREAD

**Issue by oyvindeide** [equinor/webviz-config#212]
If not strictly neccessary (like for `dash`), it would be nice if requirements were not version specific (or lower bound) instead of `~=`, as that easily causes problems with other packages. One example is pandas which is now on version `1.0.3`, so any library using that is incompatible with `webviz`.

**Comment by anders-kiaer** [comment]
Thanks @oyvindeide for the report! We should definitely open up for using the  new version `1` series of `pandas`. Ideally, in my view, we should aim for:
* As relaxed version constraints of dependencies as possible...
* ...where all dependency versions within the constraints work properly with `webviz-config`.

Using the [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release) operator, pinning only the major version number `x` (assuming semantic versioning `x.y.z`), is one way of doing a compromise between the bullet points above. We tell the users that it will work for a given major version series, at the same time as they are free to upgrade beyond the specified minor version. The users then also get an easy to understand version conflict error message during installation, instead of potentially less intuitive errors due to new major version (with breaking changes) of one of the dependencies. A potential problem though occurs, as here with `pandas`, when a direct dependency releases a new major version.

Maybe a good solution could be to use `~=` (still pinning only major version), but add to CI a check if any of the direct dependencies has a new major version. And around the release of a new major version (of one of the dependencies) we support multiple major versions (adding them to the CI matrix).

E.g. for `pandas` we probably want to support and run CI tests with `pandas ~= 0.24` and `pandas ~= 1.0` (since RHEL6 is used internally, which doesn't support `pandas >= 0.25`). The corresponding `setup.py` version constraint would then be `pandas >= 0.24, < 2`.

What do you think?

**Comment by oyvindeide** [comment]
Of course there are some considerations to make with regards to compatibility, but I would argue that specifying it for all dependencies is overly restrictive and I´m quite sure `webviz-config` is compatible with much looser requirements as many of the packages have very stable APIs. From: https://packaging.python.org/discussions/install-requires-vs-requirements/

>It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades. 

And considering how actively developed `webviz-config` is, it is better for the users to have flexibility, and fix any compatibility issues in the code instead of pinning versions. There is also the additional risk of deprecations pilling up as they are not noticed as the version doesn´t change.

As you point out you have to be compatible with RHEL6, but I would argue that is not really a consideration of `setup.py`, and I like your solution of CI instead. It could be solved by having integration tests against `komodo` for example.

Just my 2 cents :)

**Comment by anders-kiaer** [comment]
👍 Thanks @oyvindeide - sounds good. Let us move from `~=` to `>=`, and extend CI matrix to test across selected versions where necessary. 

We plan to move from Travis CI/CD to GitHub workflow CI/CD shortly (within this week) - I can probably do this change at the same time. We might then be able to also utilize [regular scheduled runs](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule). Then the `webviz-config` maintainers can be notified if there is any new dependency releases that break the current code base.
