### ISSUE TITLE
Prefer Firefox over Chrome

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-config#378]
After #374 we don't need `webviz certificate --auto-install` anymore. 
Switching the preferred browser to `firefox`, unless overruled by `webviz preferences`, will make the conversion on `localhost` smoother, as no actions are required by the end user due to the certificate change.

https://github.com/equinor/webviz-config/blob/ee4b40323b5b3dda567c4eabcd6f80754e744e6a/webviz_config/utils/_localhost_open_browser.py#L59-L63

**Comment by dotfloat** [comment]
I'll think about whether it's possible to solve #288 instead. We'd rather use the user's default browser unless it's too old, in which case we provide eg. Firefox. This isn't something that's possible to do via the `webbrowser` module since it's a bit dumb, but could perhaps be possible with some extra Python code.

**Comment by asnyv** [comment]
@dotfloat 👍 Think we'll have to do at least one of them before the next release to make the transition as smooth as possible. 
But to add Firefox as preferred is of course super simple, so can wait until we are close to feature freeze.

**Comment by dotfloat** [comment]
I agree. We could probably just do Firefox now and then later on do #288.
